### ISSUE TITLE
Ryven | Load Example | demo_example.json can't find PythonOCC

### ISSUE THREAD

**Issue by WillAdams** [Tanneguydv/Pythonocc-nodes-for-Ryven#11]
Click on "AUTO IMPORT" and it finds std but can't find PythonOCC

**Comment by leon-thomm** [comment]
yes, it doesn't know where the nodes package is, because when the creator of the project used it on his machine, it was under a different path. you need to locate it manually: click on `ADD`, navigate to your clone of this repo and select `Pythonocc-nodes-for-Ryven/PythonOCC/nodes.py`. If you then save the project on your machine it will update the paths in the project file and you don't have to locate it again next time

**Comment by WillAdams** [comment]
I don't understand "clone of this repo"?

Wasn't it installed by the command "conda install -c conda-forge pythonocc-core"?

**Comment by leon-thomm** [comment]
pythonocc-core is a prerequisite (or dependency), along with pythonocc-utils, anaconda, and ryven. if you want to use this project (Pythonocc-nodes-for-Ryven), you have to download it too, i.e. clone the repository via `git clone https://github.com/Tanneguydv/Pythonocc-nodes-for-Ryven`

**Comment by WillAdams** [comment]
I guess the thing which I'm missing here is the difference between just using python at the terminal, using anaconda, and the difference in accessing one or the other.

Is there a set of step-by-step instructions, which assume nothing, for installing on Linux?

What happened to the pythonocc.org website?

**Comment by leon-thomm** [comment]
yeah, I don't know if there are more detailed instructions for PythonOCC, but you will find plenty of resources online which take you through the process of installing the Anaconda platform, setting up a new conda environment, and then installing packages in this environment, which is what you need.

**Comment by leon-thomm** [comment]
and to prevent confusion: you can have (and usually do) have various Python installations on your system, and Anaconda will also bring its own Python installation. So, yes you are using Python, but you use it inside an Anaconda environment

**Comment by Tanneguydv** [comment]
Once everything installed you can create a` .bat` file with this text :
```
call activate pyoccryv3env
ryven
pause
```
Then create a shortcut of this ` .bat` file to havae easy access to Ryven.

Personnaly I use Miniconda instead of Anaconda, and I use Pycharm to easily access virtual environnement and code in a python friendly IDE

**Comment by WillAdams** [comment]
The problem seems to be that I can't get a working nodes.py loaded.

I've downloaded and unzipped: https://github.com/Tanneguydv/Pythonocc-nodes-for-Ryven/archive/refs/heads/main.zip

and if I point it at:

![image](https://user-images.githubusercontent.com/3543154/152080869-fc93ae38-145f-4dd3-88b7-d412ed3861f5.png)

get:

![image](https://user-images.githubusercontent.com/3543154/152080883-e791cc4c-6103-4f2f-ba0f-1f330a303e2a.png)

and if I point it at:

![image](https://user-images.githubusercontent.com/3543154/152080955-338bffaa-b794-4047-91e7-9bd41c6b1b73.png)

the same

and if both:

![image](https://user-images.githubusercontent.com/3543154/152081112-2a94fd86-a1d5-4d57-9fbb-d992537fe3ca.png)

(base) C:\Users\willa>ryven
importing packages...
Traceback (most recent call last):
  File "C:\Users\willa\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\willa\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\willa\AppData\Local\Programs\Python\Python310\Scripts\ryven.exe\__main__.py", line 7, in <module>
  File "C:\Users\willa\AppData\Local\Programs\Python\Python310\lib\site-packages\ryven\main\Ryven.py", line 75, in run
    editor = MainWindow(editor_init_config, window_title, window_theme, flow_theme, parent=gui_parent)
  File "C:\Users\willa\AppData\Local\Programs\Python\Python310\lib\site-packages\ryven\gui\main_window.py", line 77, in __init__
    self.import_packages(config['required packages'])
  File "C:\Users\willa\AppData\Local\Programs\Python\Python310\lib\site-packages\ryven\gui\main_window.py", line 324, in import_packages
    self.import_nodes(p)
  File "C:\Users\willa\AppData\Local\Programs\Python\Python310\lib\site-packages\ryven\gui\main_window.py", line 334, in import_nodes
    nodes = import_nodes_package(p)
  File "C:\Users\willa\AppData\Local\Programs\Python\Python310\lib\site-packages\ryven\main\utils.py", line 48, in import_nodes_package
    load_from_file(package.file_path)
  File "C:\Users\willa\AppData\Local\Programs\Python\Python310\lib\site-packages\ryven\main\utils.py", line 19, in load_from_file
    mod = spec.loader.load_module(name)
  File "<frozen importlib._bootstrap_external>", line 548, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1063, in load_module
  File "<frozen importlib._bootstrap_external>", line 888, in load_module
  File "<frozen importlib._bootstrap>", line 287, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 619, in _exec
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\willa\Desktop\Xtensions\Pythonocc-nodes-for-Ryven-main\nodes.py", line 3, in <module>
    widgets = import_widgets(__file__)
  File "C:\Users\willa\AppData\Local\Programs\Python\Python310\lib\site-packages\ryven\NENV.py", line 81, in import_widgets
    load_from_file(abs_path)
  File "C:\Users\willa\AppData\Local\Programs\Python\Python310\lib\site-packages\ryven\main\utils.py", line 19, in load_from_file
    mod = spec.loader.load_module(name)
  File "<frozen importlib._bootstrap_external>", line 548, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1063, in load_module
  File "<frozen importlib._bootstrap_external>", line 888, in load_module
  File "<frozen importlib._bootstrap>", line 287, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 619, in _exec
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\willa\\Desktop\\Xtensions\\Pythonocc-nodes-for-Ryven-main\\widgets.py'

**Comment by Tanneguydv** [comment]
I think that your installation of Ryven does not belong to the virtual environment created with OCC installation, that's why the module OCC can't be found while launching Ryven I guess.
At the installation of OCC you created a virtual env (named such as `pyoccenv`), you have to install Ryven in this same virtual environment (`conda activate pyoccenv` then `pip install ryven`)

**Comment by leon-thomm** [comment]
@Tanneguydv what is the difference between the two nodes files? there should only be one in `PythonOCC/`

**Comment by Tanneguydv** [comment]
There's only one node file, no?

**Comment by leon-thomm** [comment]
`repo/nodes.py`
https://github.com/Tanneguydv/Pythonocc-nodes-for-Ryven/blob/main/nodes.py
`repo/PythonOCC/nodes.py`
https://github.com/Tanneguydv/Pythonocc-nodes-for-Ryven/blob/main/PythonOCC/nodes.py
which caused some confusion above, there should only be 1

#14

**Comment by Tanneguydv** [comment]
My Bad, I'll fix this

**Comment by Tanneguydv** [comment]
removed, I closed your pull request, thank you!

**Comment by WillAdams** [comment]
Okay, the command:

source activate pyoccenv

from: https://github.com/tpaviot/pythonocc-core doesn't seem to work --- instead used:

conda activate pyoccenv

and then installing pythonocc resulted in:

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pythonocc-core=7.5.1 -> python[version='2.7.*|3.5.*|3.6.*|3.8.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|3.4.*|>=3.5,<3.6.0a0|3.9.*|3.7.*']
  - pythonocc-core=7.5.1 -> python[version='>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']

Your python: python=3.10

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package zlib conflicts for:
python=3.10 -> zlib[version='>=1.2.11,<1.3.0a0']
occt=7.5.1 -> freeimage[version='>=3.18.0,<3.19.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']

Package bzip2 conflicts for:
python=3.10 -> bzip2[version='>=1.0.8,<2.0a0']
pythonocc-core=7.5.1 -> python[version='>=3.9,<3.10.0a0'] -> bzip2[version='>=1.0.8,<2.0a0']
Note that strict channel priority may have removed packages required for satisfiability.
