### ISSUE TITLE
Example file torus_gcode.json has Unicode error w/ Miniconda

### ISSUE THREAD

**Issue by WillAdams** [Tanneguydv/Pythonocc-nodes-for-Ryven#16]
As noted in the discussion, when this is loaded on a Windows machine:

Traceback (most recent call last):
File "C:\Users\willa\miniconda3\envs\pyoccenv\lib\site-packages\ryven\gui\startup_dialog\StartupDialog.py", line 99, in load_example_project_button_clicked
self.open_project(base_dir=abs_path_from_package_dir('examples_projects'))
File "C:\Users\willa\miniconda3\envs\pyoccenv\lib\site-packages\ryven\gui\startup_dialog\StartupDialog.py", line 122, in open_project
project_str = f.read()
File "C:\Users\willa\miniconda3\envs\pyoccenv\lib\encodings\cp1252.py", line 23, in decode
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 161607: character maps to

Would this be different for Anaconda vs. Miniconda?

**Comment by leon-thomm** [comment]
seems like a pythonocc issue :thinking:

**Comment by WillAdams** [comment]
Could it have something to do w/ it wanting to load Dev?

![image](https://user-images.githubusercontent.com/3543154/152628658-f97d0753-0a98-4492-8a36-d887c016c62c.png)

**Comment by Tanneguydv** [comment]
Indeed you have to edit the dir of the required package in the .json file
```
  "required packages": [
        {
            "name": "PythonOCC",
            "dir": "C:/Users/nutri/projects/ryven projects/Pythonocc-nodes-for-Ryven/PythonOCC"
        }
```
